import type { ProjectRecord } from "@/lib/types";

export const sampleProjects: ProjectRecord[] = [
  {
    id: "capital-project-1001",
    source_type: "capital_project",
    source_id: "1001",
    name: "Protected Bike Lane Safety Upgrades",
    status: "planned",
    ward: "5",
    mode: "bike",
    description:
      "Concept project for safer north-south bike access with intersection daylighting and protected space at key blocks.",
    timeline_start: "2026-07-01",
    timeline_end: "2027-03-31",
    cost: 1250000,
    official_url: null,
    geometry: { type: "Point", coordinates: [-76.9959, 38.9128] },
    raw: { demo: true },
    synced_at: new Date().toISOString(),
  },
  {
    id: "trail-project-2204",
    source_type: "trail_project",
    source_id: "2204",
    name: "Metropolitan Branch Trail Connection",
    status: "active",
    ward: "4",
    mode: "trail",
    description:
      "Trail segment improvements focused on closing a neighborhood access gap and improving crossings.",
    timeline_start: "2026-02-01",
    timeline_end: "2026-12-31",
    cost: 3100000,
    official_url: null,
    geometry: {
      type: "LineString",
      coordinates: [
        [-77.0172, 38.9397],
        [-77.0119, 38.9455],
        [-77.0067, 38.9511],
      ],
    },
    raw: { demo: true },
    synced_at: new Date().toISOString(),
  },
  {
    id: "art-installation-301",
    source_type: "art_installation",
    source_id: "301",
    name: "Neighborhood Traffic Box Art",
    status: "complete",
    ward: "1",
    mode: "art",
    description:
      "Completed streetscape art installation near a high-foot-traffic commercial corridor.",
    timeline_start: "2025-04-01",
    timeline_end: "2025-08-01",
    cost: 45000,
    official_url: null,
    geometry: { type: "Point", coordinates: [-77.032, 38.917] },
    raw: { demo: true },
    synced_at: new Date().toISOString(),
  },
];
