insert into public.features (
  id,
  source_type,
  source_id,
  name,
  status,
  ward,
  mode,
  description,
  timeline_start,
  timeline_end,
  cost,
  official_url,
  geometry,
  raw
) values
  (
    'capital-project-1001',
    'capital_project',
    '1001',
    'Protected Bike Lane Safety Upgrades',
    'planned',
    '5',
    'bike',
    'Concept project for safer north-south bike access with intersection daylighting and protected space at key blocks.',
    '2026-07-01',
    '2027-03-31',
    1250000,
    null,
    '{"type":"Point","coordinates":[-76.9959,38.9128]}'::jsonb,
    '{"demo":true}'::jsonb
  ),
  (
    'trail-project-2204',
    'trail_project',
    '2204',
    'Metropolitan Branch Trail Connection',
    'active',
    '4',
    'trail',
    'Trail segment improvements focused on closing a neighborhood access gap and improving crossings.',
    '2026-02-01',
    '2026-12-31',
    3100000,
    null,
    '{"type":"LineString","coordinates":[[-77.0172,38.9397],[-77.0119,38.9455],[-77.0067,38.9511]]}'::jsonb,
    '{"demo":true}'::jsonb
  ),
  (
    'art-installation-301',
    'art_installation',
    '301',
    'Neighborhood Traffic Box Art',
    'complete',
    '1',
    'art',
    'Completed streetscape art installation near a high-foot-traffic commercial corridor.',
    '2025-04-01',
    '2025-08-01',
    45000,
    null,
    '{"type":"Point","coordinates":[-77.032,38.917]}'::jsonb,
    '{"demo":true}'::jsonb
  )
on conflict (id) do update set
  source_type = excluded.source_type,
  source_id = excluded.source_id,
  name = excluded.name,
  status = excluded.status,
  ward = excluded.ward,
  mode = excluded.mode,
  description = excluded.description,
  timeline_start = excluded.timeline_start,
  timeline_end = excluded.timeline_end,
  cost = excluded.cost,
  official_url = excluded.official_url,
  geometry = excluded.geometry,
  raw = excluded.raw,
  synced_at = now();
